### ISSUE TITLE
Tracking link hits.

### ISSUE THREAD

**Issue by NoahvdAa** [NoahvdAa/S.H.O.R.T.#2]
Add some sort of system, that tracks the amount of hits a link has received. This should be stored as a number in the KeyV database (for example as hits-<shortID>, so e.g. hits-waakzg). An API endpoint that returns this number (e.g. /api/hits/:id) should also be added, along with a page that lets you enter an id and returns the amount of hits.

**Comment by jasbindar-singh** [comment]
Step 1: Whenever a link is shortened we also save a hit-`id` to be 0.
Step 2: Now when the link /:id is hit we check if the id exists, if yes fetch hit-`id` as well, increment and save it, and redirect. 
Step 3: Create an API /api/hits/:id to fetch the number of hits.
If the flow is clear, can I work on it?

**Comment by NoahvdAa** [comment]
> Step 1: Whenever a link is shortened we also save a hit-`id` to be 0.
> Step 2: Now when the link /:id is hit we check if the id exists, if yes fetch hit-`id` as well, increment and save it, and redirect.
> Step 3: Create an API /api/hits/:id to fetch the number of hits.
> If the flow is clear, can I work on it?

That's correct, go ahead :)
